### ISSUE TITLE
Implement Jazzband guidelines for project django-embed-video

### ISSUE THREAD

**Issue by jezdez** [jazzband/roadies#163]
This issue tracks the implementation of the [Jazzband guidelines](https://jazzband.co/about/guidelines) for the project [django-embed-video](https://github.com/jazzband/django-embed-video)

It was initiated by @yetty who was automatically assigned in addition to the [Jazzband roadies](https://jazzband.co/roadies).

See the [TODO list](#todos) below for the generally required tasks, but feel free to update it in case the project requires it.

Feel free to ping a [Jazzband roadie](https://jazzband.co/roadies) if you have any question.

## TODOs<a name="todos"></a>

- [x] Fix all links in the docs (and README file etc) from old to new repo
- [x] Add the [Jazzband badge](https://jazzband.co/about/guidelines#badges) to the `README` file
- [x] Add the [Jazzband contributing guideline](https://jazzband.co/about/guidelines#contributing-guidelines) to the `CONTRIBUTING.md` file
- [x] Check if continuous testing works (e.g. [Travis-CI](https://travis-ci.org/), [CircleCI](https://circleci.com), [AppVeyor](https://www.appveyor.com), etc)
- [x] Check if test coverage services work (e.g. [Coveralls](https://coveralls.io), [Codecov](https://codecov.io), etc)
- [x] Add `jazzband` account to [PyPI](https://pypi.org/) project as maintainer role (e.g. URL: `https://pypi.org/manage/project/<PROJECTNAME>/collaboration/`)
- [x] Add `jazzband-bot` as maintainer to the [Read the Docs](https://readthedocs.org/) project (URL: `https://readthedocs.org/dashboard/<PROJECTNAME>/users/`)
- [x] Fix project URL in [GitHub project](https://github.com/jazzband/django-embed-video) description
- [x] Review project if other services are used and port them to Jazzband
- [x] Decide who is project lead for the project (if at all) and setup CI for it if needed

**Comment by jezdez** [comment]
@aleksihakli @yetty Would you two mind going through the list above and check/fix the rest of the open items?

**Comment by aleksihakli** [comment]
Sure, I'll go over the list and the project. The RTD and repo settings are inaccessible for me, but I'll check and update references inside the repository.

**Comment by yetty** [comment]
jazzband-bot added as a maintainer to the RTD.

**Comment by aleksihakli** [comment]
Everything should be in order now.

**Comment by jezdez** [comment]
I've also set up the RTD webhook in the repo. Closing since we're done here.
